name: CI

on:
  push:
    branches: [ main ]

jobs:

  default:
    name: Default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: NPM install
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Semantic release
        if: github.ref == 'refs/heads/main'
        run: npx --no-install semantic-release --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
